export const MOETEPLANLEGGER = "MOETEPLANLEGGER"; // TODO: Bytte navn til DIALOGMOTER
export const NOKKELINFORMASJON = "NOKKELINFORMASJON";
export const SYKMELDINGER = "SYKMELDINGER";
export const SYKEPENGESOKNADER = "SYKEPENGESOKNADER";
export const OPPFOELGINGSPLANER = "OPPFOELGINGSPLANER";
export const HISTORIKK = "HISTORIKK";
export const VEDTAK = "VEDTAK";
