apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: teamsykefravr
  name: syfomodiaperson-redisexporter
  namespace: teamsykefravr
spec:
  image: oliver006/redis_exporter:v1.20.0
  port: 9121
  prometheus:
    enabled: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
  liveness:
    path: /health
  accessPolicy: # for GCP
    outbound:
      rules:
        - application: syfomodiaperson-redis
  env:
    - name: REDIS_ADDR
      value: syfomodiaperson-redis:6379
    - name: REDIS_EXPORTER_LOG_FORMAT
      value: json
  envFrom:
    - secret: syfomodiaperson-redis-password
