export const PERSONKORTVISNING_TYPE = {
  SYKMELDT: "SYKMELDT",
  LEDER: "LEDER",
  LEGE: "LEGE",
  ENHET: "ENHET",
  SIKKERHETSTILTAK: "SIKKERHETSTILTAK",
};

export const KJOENN = {
  KVINNE: "KVINNE",
  MANN: "MANN",
};
